[tool.poetry]
name = "automation-ciena"
version = "0.1.0"
description = ""
authors = ["Kenfelix"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
netmiko = "^4.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
